[workspace]
resolver = "2"
members = [
    "crates/doca-ipc",
    "crates/docad",
    "crates/doca-shell",
    "crates/doca-prefs",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.75"

[workspace.dependencies]
doca-ipc = { path = "crates/doca-ipc" }
zbus = "5"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "signal", "time"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
