[package]
name = "doca-shell"
version.workspace = true
edition.workspace = true

[[bin]]
name = "doca-shell"
path = "src/main.rs"

[dependencies]
doca-ipc.workspace = true
zbus.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
gtk = "0.18"
gdk = "0.18"
gdkx11 = "0.18"
glib = "0.18"
pango = "0.18"
pangocairo = "0.18"
x11rb = "0.13"
futures-util = "0.3"
async-channel = "2"
